### ISSUE TITLE
Cases Where `get_context_data` Does Not Need to be Overridden

### ISSUE THREAD

**Issue by vjlomocso** [destiny07/ProjectRR#1]
locations:
- [`DetailRequestView`](https://github.com/destiny07/ProjectRR/blob/ams/site_core/views.py#L36)
- [`DetailRacketView`](https://github.com/destiny07/ProjectRR/blob/ams/site_core/views.py#L77)
- [`DetailUploadView`](https://github.com/destiny07/ProjectRR/blob/ams/site_core/views.py#L162)

ngano diay ni ang:
```python
def get_context_data(self, **kwargs):
    context = super(DetailRequestView, self).get_context_data(**kwargs)
               # or DetailRacketView
               # or DetailUploadView
    return context
```
It makes no changes to the default method...
Unless there is a good reason for it, I suggest wala nalay `get_context_data` para less function overhead :)

**Comment by amse-it** [comment]
(y)
