### ISSUE TITLE
Where `get_queryset` Does Not Need to be Overridden

### ISSUE THREAD

**Issue by vjlomocso** [destiny07/ProjectRR#2]
sa [`ListUploadView`](https://github.com/destiny07/ProjectRR/blob/ams/site_core/views.py)
kaning:
```python
    def get_queryset(self):
        return models.Upload.objects.all()
```
You can replace `get_queryset` with `model = models.Upload`

**Comment by amse-it** [comment]
:+1:    :smiley:
